### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by ak868308** [ratacibernetica/yii2-node-socket#3]
Hello friend,
This is really really useful for me but "No 'Access-Control-Allow-Origin' header is present on the requested resource" is annoying me. 
I tried more with client.js but I am unable to resolve the same.
Please help me ASAP
I am using Yii2 and I placed 'https://cdn.socket.io/socket.io-1.3.5.js' directly into the NodeSocketAssets
instead of 
"http://%s:%d%s", Yii::$app->nodeSocket->host, Yii::$app->nodeSocket->port, '/socket.io/socket.io.js'
![socket client](https://cloud.githubusercontent.com/assets/7982249/16376294/26ec82e6-3c7d-11e6-84e3-50741c3a2c84.PNG)

I already followed the steps which you explained in documentation.
this is the code of my view file 

$js = <<<JS
// create object
var socket = new YiiNodeSocket();

JS;
 $this->registerJs($js, \yii\web\View::POS_READY);

**Comment by manuel-ojeda** [comment]
Did you solved it? how?

**Comment by ak868308** [comment]
Yes I did that with a single statement
I placed in my Layout -  header("Access-Control-Allow-Origin: *");

and its done
